GoalDetector: Needs testing
FTCLib/FTCLib pull request #101
Opened 2020-10-12 01:20 UTC by codeNinjaDev

**Very janky code**. I struggled with differentiating three different cases for powershot detection: 

1. Camera is between Powershot and HighGoal
2. The angle to the HighGoal includes the angle to the Powershot
3. Angle to Powershot is separate from the angle to the HighGoal

In addition to the AdvancedHighGoalPipeline (Powershot calculations), I created Pipelines to track pixel values & angles of Highgoal.

![image](https://user-images.githubusercontent.com/19578618/95695978-e9615180-0bfe-11eb-85a3-10a5dcc1712c.png "Case 2")
![image](https://user-images.githubusercontent.com/19578618/95696016-1150b500-0bff-11eb-9e92-6bd716944b17.png "Case 3")

2020-10-12 01:46 UTC, JIceberg commented
How much testing? Have edge cases been looked at yet?

2020-10-12 14:03 UTC, codeNinjaDev commented
> How much testing? Have edge cases been looked at yet?

I've tried to anticipate the above edge cases, but I haven't been able to do any testing.

2020-10-24 01:52 UTC, JIceberg commented
This PR actually doesn't work with the refactor. Can you pull from upstream and use the new layout?

2020-11-01 20:13 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAdvancedHighGoalPipeline.java
> +    }
Constructors need to have the same name as the classfile.

2020-11-01 20:14 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAngleHighGoalPipeline.java
> +    }
Constructors need to have the same name as the classfile

2020-11-01 20:14 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAngleHighGoalPipeline.java
> +public class UGAngleHighGoalPipeline extends BasicHighGoalPipeline {
Replace `BasicHighGoalPipeline` with `UGBasicHighGoalPipeline`

2020-11-01 20:15 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAdvancedHighGoalPipeline.java
> +public class UGAdvancedHighGoalPipeline extends AngleHighGoalPipeline {
Replace `AngleHighGoalPipeline` with `UGAngleHighGoalPipeline`

2020-11-01 20:15 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGBasicHighGoalPipeline.java
> +    }
Constructor should have the same name as the classfile.

2020-11-01 20:16 UTC, JIceberg requested changes
Follow these changes and it shouldn't fail the build check.

2020-11-02 23:35 UTC, codeNinjaDev commented
Opening new pull request

2020-11-02 23:35 UTC, closed without merging