Added getRectWidth, getRectHeight, and getRectSize methods in UGContourRingPipeline.kt
FTCLib/FTCLib pull request #172
Opened 2021-01-21 04:59 UTC by hudson-dev

# Added getRectWidth, getRectHeight, and getRectSize methods in UGContourRingPipeline.kt

Please note that we accept pull requests from anyone, but that does not mean it will be merged.

## What kind of change does this PR introduce?
* Feature

Added getRectWidth, getRectHeight, and getRectSize methods in UGContourRingPipeline.kt to expose the width, height, and size of the bounding box around the rings when created with the vision pipeline. 

_Please note this is my first pull request and I am fairly new to open source._

## Did this PR introduce a breaking change?
* No

__Please make sure your PR satisfies the requirements of [the contributing page](CONTRIBUTING.md)__

2021-01-21 05:56 UTC, JarnaChao09 requested changes
change all getter methods to be properties (rectWidth, rectHeight, rectSize), as this follows a more idiomatic kotlin syntax
getters are not needed as with properties of a class, getters and setters (if var) are auto generated to follow classic syntax so calling from Java will not change.

2021-01-21 06:11 UTC, serivesmejia commented
https://kotlinlang.org/docs/reference/properties.html in case you’re not sure how kotlin getters/setters work :)

2021-01-21 07:44 UTC, hudson-dev commented
@JarnaChao09 I'm not very familiar with Kotlin however I have added the rectWidth, rectHeight, and rectSize variables with getters in UGContourRingPipeline.kt.

2021-01-21 19:12 UTC, hudson-dev reviewed
I completed this in my most recent commit.

2021-01-23 16:50 UTC, JarnaChao09 requested changes
Could the variables rectWidth, rectHeight, rectSize be turned into val properties. Being var properties makes it seem like these variables are able to be changed as the setter call is a valid operation. If they were to be made val, the default value wouldn't be needed and only the getter would be a valid operation.

Could maxRect be labeled as private set? It would be counter-intuitive if the user is able to falsely give a Rect object for the pipeline to use.

2021-02-03 05:55 UTC, JarnaChao09 approved these changes

2021-02-04 18:19 UTC, puravdatta-sudo approved these changes
Looks good to merge, simple pr

2021-02-04 18:19 UTC, merged