Capstone Vision for 2021 Season
FTCLib/FTCLib pull request #200
Opened 2021-11-22 15:14 UTC by litehed

# Pull Requests

Please note that we accept pull requests from anyone, but that does not mean it will be merged.

## What kind of change does this PR introduce?
* Feature
This PR adds a pipeline and detector people can use in order to find the position of their capstones. The pipeline will look for the largest contour and return its center point. The detector will then determine the position of the objects based on the center points relative to their position on the screen.

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
* No

__Please make sure your PR satisfies the requirements of [the contributing page](CONTRIBUTING.md)__

2021-11-22 15:44 UTC, serivesmejia commented
I recommend renaming the pipeline from "Capstone" to "TeamShippingElement" ("TSE"?)

2021-11-23 23:30 UTC, litehed commented
> I recommend renaming the pipeline from "Capstone" to "TeamShippingElement" ("TSE" for a shorter one?)

I was thinking about that but then I realized FFTSEDetector would not look like the best name for a class. Or we could just separate our vision out into different packages for each season and I could Remove the FF.

2021-11-29 17:12 UTC, JarnaChao09 reviewed
Everything else looks fine, the math checks out (assuming raw moments), should be ready to merge once the 3.2 and 1.6 get resolved

2021-11-29 19:57 UTC, litehed commented
> Everything else looks fine, the math checks out (assuming raw moments), should be ready to merge once the 3.2 and 1.6 get resolved

Yeah, I was just messing around and forgot to change it back, so now it is less than 1/3 of the screen is left and greater than 2/3 is right. Also, should I make the value based on a percentage of the screen or just pixels?

2021-11-29 20:00 UTC, JarnaChao09 commented
> > Everything else looks fine, the math checks out (assuming raw moments), should be ready to merge once the 3.2 and 1.6 get resolved
> 
> Yeah, I was just messing around and forgot to change it back, so now it is less than 1/3 of the screen is left and greater than 2/3 is right. Also, should I make the value based on a percentage of the screen or just pixels?

I would say store it in pixels and just make helper functions that take in a percentage instead and then have it calculate it based on that. Some users may want more fine control while others will be like "ehhh screw it, set it to 50%"

2021-11-30 00:20 UTC, litehed commented
> 

Just made a change.
Is this what you mean?

2021-12-01 21:29 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/FFCapstonePipeline.java
> +        Mat hierarchy = new Mat();
Does this get released at some point?

2021-12-01 21:29 UTC, JIceberg commented on core/vision/src/main/java/com/arcrobotics/ftclib/vision/FFCapstonePipeline.java
> +            }
You should clarify what is meant here by "contours."

2022-01-25 22:47 UTC, JarnaChao09 requested changes
Thresholds are always something that should be left as transparent as possible. Giving the user options to define their own thresholds is important. I would look into some way of giving the user a way to define their own threshold calculations, whether it is through a new constructor, or maybe using lambdas for threshold calculation instead.

2022-01-26 13:18 UTC, litehed commented
> Thresholds are always something that should be left as transparent as possible. Giving the user options to define their own thresholds is important. I would look into some way of giving the user a way to define their own threshold calculations, whether it is through a new constructor, or maybe using lambdas for threshold calculation instead. 

In line 220 of the detector I have the option to set the threshold. Is that what you mean or do you mean setting the logic of the threshold as well?

2022-01-27 00:32 UTC, JarnaChao09 commented
> 

no, I was thinking more so you are able to change the formula used. Instead of width / 3, it would be width / 4 and the user could supply this equation through either a lambda or just doing the calculation in their own function and supplying the result.

2022-02-07 21:09 UTC, JarnaChao09 approved these changes

2022-02-07 23:40 UTC, merged