fix readme
FTCLib/FTCLib pull request #205
Opened 2022-02-10 01:58 UTC by litehed

# Pull Requests

Please note that we accept pull requests from anyone, but that does not mean it will be merged.

## What kind of change does this PR introduce?
* Feature
This PR adds a function to normalize vectors within Vector2d.

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
* No

__Please make sure your PR satisfies the requirements of [the contributing page](CONTRIBUTING.md)__

2022-02-13 01:22 UTC, JIceberg requested changes

2022-02-13 01:22 UTC, JIceberg commented on core/src/main/java/com/arcrobotics/ftclib/geometry/Vector2d.java
> +    }
Why is the normalization happening with an input?
Normalization is typically defined as scaling all elements of the vector such that the dot product with itself is 1.
I think that the method should be
```java
public Vectoe2d norm() {
  return scale(1 / magnitude());
}
```
Can you explain further as to why there is a parameter here?

2022-02-13 01:25 UTC, JIceberg commented on core/src/main/java/com/arcrobotics/ftclib/geometry/Vector2d.java
> +    }
That's not normalization.

2022-02-13 01:38 UTC, JIceberg approved these changes

2022-02-16 18:30 UTC, JarnaChao09 approved these changes

2022-02-19 17:49 UTC, merged