Feature kotlin extensions
FTCLib/FTCLib pull request #99
Opened 2020-10-05 04:15 UTC by JarnaChao09

uwu, pwease mewge mwy pwuwww weqwest into mwastew, senpai~! OwO

fow uw pr, pwease make suwwe it answews the fowwowing:
## what kind of change does this pr intwoduwce? UwU
* stywish code uwwuw

adds syntactic sugars for Kotlin users of FTCLib

this does not add any breaking changes

2020-10-05 04:21 UTC, JarnaChao09 commented
Do not merge, will change `in` to input and output for all LUT related files

2020-10-05 18:13 UTC, JIceberg commented
Converted to draft

2020-10-12 01:32 UTC, JIceberg commented
Yo but did it work tho @JarnaChao09

2020-10-12 22:27 UTC, JIceberg commented on core/src/main/java/com/arcrobotics/ftclib/kotlin/extensions/drivebase/RobotDriveExt.kt
> +
Required comment that explains what this class is doing for the extension.

2020-10-12 22:28 UTC, JIceberg commented on core/src/main/java/com/arcrobotics/ftclib/kotlin/extensions/geometry/Pose2dExt.kt
> +
Needs a comment that explains what this class is doing for the extension.

2020-10-12 22:28 UTC, JIceberg commented on core/src/main/java/com/arcrobotics/ftclib/kotlin/extensions/geometry/Rotation2dExt.kt
> +
Needs a comment that explains what this class is doing for the extension.

2020-10-12 22:29 UTC, JIceberg requested changes
Please add comments at the top of each class that explains what it is doing along with its purpose.

2020-10-19 17:22 UTC, JIceberg approved these changes
Looks good.

2020-10-19 17:22 UTC, merged